apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuks-app
  labels:
    app: chuks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chuks-app
  template:
    metadata:
      labels:
        app: chuks-app
    spec:
      containers:
      - name: simple-node-travis
        image: chuksonu/simple-node-travis
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: test/actuator/health
            port: 9001
          initialDelaySeconds: 3
          periodSeconds: 3
